### ISSUE TITLE
Pain

### ISSUE THREAD

**Issue by Zinnig** [nHexanol/TAq-Public#1]

**Comment by nHexanol** [comment]
Fixed ( kinda )

**Comment by Zinnig** [comment]
|Line(s)|Issue|Replacement|
|----|-----|--------------|
|29, 30, 31, 33, 34, 40, 88| useless replace spam | `.replace(/"/g,' ')` and `.replace(/null/g,' ')`|
|29-34, 37-38, 85-86, 144, 167-167, 174-175, | remove useless `JSON.stringify()` (if you add the values to a string they'll become a string either way) | - |
|100, 111| uhm replace go brr?| `.replace(/ /g, '+')`|
|153| more replace spam| `.replace(/"/g, '')`|
|181-186| Simplify adding the fields | ``addFields({ name: 'The Aquarium [TAq]', value: `Level ${level} \| ${xp} %`},{ name: 'The FishTank [FTk]', value: `Level ${flevel} \| ${fxp} %`},)``
|196-207| Simplify adding the fields | `.addFields({ name: '/l', value: 'Check TAq and FTk current level' }, { name: '/ck <Username>', value: 'Basic player stats check' },{ name: '/xp', value: 'Unfinished unsorted XP leaderboard' },{ name: '/ls', value:'Unfinished online guild member (might hit rate limit)' },)`|

Or leave it empty and use the [link text itself].

Also please decide if you're going to use semicolons or not, because atm they're sometimes there and sometimes not.
Read this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat
That should be all for now
